package businessrule.usecase.util;

import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 * This class represents a utility for executing Python scripts and reading their output.
 */
public class PythonReader {

    /**
     * Executes a Python command and reads the output.
     *
     * @param command The Python command to execute.
     * @return The output generated by the Python script.
     */
    public String readPythonExec(String command) {
        Process proc;
        try {
            proc = Runtime.getRuntime().exec(command);
            proc.waitFor();
            InputStream inputStream = proc.getInputStream();
            InputStream errorStream = proc.getErrorStream();
            String errorOutput = IOUtils.toString(errorStream, StandardCharsets.UTF_8);
            if (!errorOutput.isEmpty()) {
                System.err.println("Error from Python: " + errorOutput);
            }
            return IOUtils.toString(inputStream, StandardCharsets.UTF_8);
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
        return null;
    }
}
